# Generated by Django 5.0.6 on 2025-04-02 14:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=17, verbose_name='ISBN')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('photo', models.TextField(verbose_name='Фото')),
                ('genre', models.CharField(choices=[('Фэнтези', 'Фэнтези'), ('Фантастика', 'Фантастика '), ('Любовный роман', 'Любовный роман'), ('Детектив', 'Детектив'), ('Приключения', 'Приключения'), ('Классическая проза', 'Классическая проза'), ('Современная проза', 'Современная проза')], max_length=30, verbose_name='Жанр')),
                ('num_page', models.SmallIntegerField(blank=True, null=True, verbose_name='Страницы')),
                ('year', models.DateTimeField(blank=True, null=True, verbose_name='Год выпуска')),
                ('discount', models.PositiveSmallIntegerField(verbose_name='Цена')),
                ('sale', models.CharField(choices=[('10', '10'), ('15', '15'), ('20', '20'), ('25', '25'), ('30', '30')], max_length=3, null=True, verbose_name='Скидка')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'книгу',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.CreateModel(
            name='PublishingHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_publish', models.CharField(max_length=50, verbose_name='Название')),
                ('photo_publish', models.TextField(blank=True, null=True, verbose_name='Фото')),
                ('publish_description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'запись об издательстве',
                'verbose_name_plural': 'Издательства',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('Апрелевка', 'Апрелевка'), ('Балашиха', 'Балашиха'), ('Бронницы', 'Бронницы'), ('Верея', 'Верея'), ('Видное', 'Видное'), ('Волоколамск', 'Волоколамск'), ('Воскресенск', 'Воскресенск'), ('Высоковск', 'Высоковск'), ('Голицыно', 'Голицыно'), ('Дзержинский', 'Дзержинский'), ('Дмитров', 'Дмитров'), ('Долгопрудный', 'Долгопрудный'), ('Домодедово', 'Домодедово'), ('Дрезна', 'Дрезна'), ('Дубна', 'Дубна'), ('Егорьевск', 'Егорьевск'), ('Жуковский', 'Жуковский'), ('Зарайск', 'Зарайск'), ('Звенигород', 'Звенигород'), ('Ивантеевка', 'Ивантеевка'), ('Истра', 'Истра'), ('Кашира', 'Кашира'), ('Климовск', 'Климовск'), ('Клин', 'Клин'), ('Коломна', 'Коломна'), ('Королев', 'Королев'), ('Котельники', 'Котельники'), ('Красноармейск', 'Красноармейск'), ('Красногорск', 'Красногорск'), ('Краснозаводск', 'Краснозаводск'), ('Краснознаменск', 'Краснознаменск'), ('Кубинка', 'Кубинка'), ('Куровское', 'Куровское'), ('Ликино-Дулево', 'Ликино-Дулево'), ('Лобня', 'Лобня'), ('Лосино-Петровский', 'Лосино-Петровский'), ('Луховицы', 'Луховицы'), ('Лыткарино', 'Лыткарино'), ('Можайск', 'Можайск'), ('Мытищи', 'Мытищи'), ('Наро-Фоминск', 'Наро-Фоминск'), ('Ногинск', 'Ногинск'), ('Одинцово', 'Одинцово'), ('Ожерелье', 'Ожерелье'), ('Орехово-Зуево', 'Орехово-Зуево'), ('Павловский Посад', 'Павловский Посад'), ('Пересвет', 'Пересвет'), ('Подольск', 'Подольск'), ('Протвино', 'Протвино'), ('Пушкино', 'Пушкино'), ('Пущино', 'Пущино'), ('Раменское', 'Раменское'), ('Реутов', 'Реутов'), ('Рошаль', 'Рошаль'), ('Руза', 'Руза'), ('Сергиев Посад', 'Сергиев Посад'), ('Серпухов', 'Серпухов'), ('Солнечногорск', 'Солнечногорск'), ('Старая Купавна', 'Старая Купавна'), ('Ступино', 'Ступино'), ('Талдом', 'Талдом'), ('Фрязино', 'Фрязино'), ('Химки', 'Химки'), ('Хотьково', 'Хотьково'), ('Черноголовка', 'Черноголовка'), ('Чехов', 'Чехов'), ('Шатура', 'Шатура'), ('Шаховская', 'Шаховская'), ('Щелково', 'Щелково'), ('Щербинка', 'Щербинка'), ('Электрогорск', 'Электрогорск'), ('Электросталь', 'Электросталь'), ('Электроугли', 'Электроугли'), ('Юбилейный', 'Юбилейный'), ('Яхрома', 'Яхрома')], max_length=20, verbose_name='Город')),
                ('street', models.TextField(verbose_name='Адрес')),
                ('transport', models.TextField(blank=True, null=True, verbose_name='Траспорт')),
                ('google_maps_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на Google Maps')),
            ],
            options={
                'verbose_name': 'запись о магазине',
                'verbose_name_plural': 'Магазины',
            },
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=60, verbose_name='Псевдоним')),
                ('photo_writ', models.TextField(default='https://vmulebki.gosuslugi.ru/netcat_files/9/148/1.jpg', verbose_name='Фото')),
                ('biography', models.TextField(blank=True, null=True, verbose_name='Биография')),
            ],
            options={
                'verbose_name': 'запись о писателе',
                'verbose_name_plural': 'Писатели',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(blank=True, max_length=30, null=True, verbose_name='Фамилия')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя')),
                ('birthday', models.DateField(blank=True, verbose_name='День рождения')),
                ('photo_acc', models.ImageField(blank=True, null=True, upload_to='profile_photos/', verbose_name='Фото профиля')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'профиль пользователя',
                'verbose_name_plural': 'Аккаунты',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_article', models.CharField(max_length=100, verbose_name='Название')),
                ('photo_article', models.TextField(blank=True, null=True, verbose_name='Фото')),
                ('text_article', models.TextField(verbose_name='Содержание')),
                ('id_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='id_bk')),
            ],
            options={
                'verbose_name': 'статью',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='id_bk')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='id_us')),
            ],
            options={
                'verbose_name': 'запись об избранном товаре',
                'verbose_name_plural': 'Избранное',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ord', models.DateField(auto_now_add=True, verbose_name='Дата заказа')),
                ('status_ord', models.CharField(choices=[('Обрабатывается', 'Обрабатывается'), ('На сборке', 'На сборке'), ('В пути', 'В пути'), ('Готов к выдаче', 'Готов к выдаче'), ('Выполнен', 'Выполнен'), ('Отменен', 'Отменен')], max_length=15, verbose_name='Статус')),
                ('price', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Сумма заказа')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts/', verbose_name='Чек')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='id_us')),
                ('id_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.shop', verbose_name='id_sp')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-date_ord'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_ord', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=2, verbose_name='Количество')),
                ('id_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitem', to='books.book', verbose_name='id_bk')),
                ('no_ord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitem', to='books.order', verbose_name='Номер заказа (id)')),
            ],
            options={
                'verbose_name': 'запись о купленном товаре',
                'verbose_name_plural': 'Позиции заказов',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='id_publish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.publishinghouse', verbose_name='id_pb'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_review', models.TextField(verbose_name='Текст отзыва')),
                ('rating', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=2, verbose_name='Рейтинг')),
                ('status_rev', models.CharField(choices=[('Обрабатывается', 'Обрабатывается'), ('Опубликован', 'Опубликован'), ('Отказ в публикации', 'Отказ в публикации')], max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания отзыва')),
                ('id_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='books.book', verbose_name='id_bk')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to=settings.AUTH_USER_MODEL, verbose_name='id_us')),
            ],
            options={
                'verbose_name': 'отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_cart', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=2, verbose_name='Количество')),
                ('id_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='id_bk')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='id_us')),
            ],
            options={
                'verbose_name': 'товар в корзине',
                'verbose_name_plural': 'Корзина',
            },
        ),
        migrations.AddField(
            model_name='publishinghouse',
            name='id_writers',
            field=models.ManyToManyField(to='books.writer', verbose_name='id_wr'),
        ),
        migrations.CreateModel(
            name='BookWriter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Главный автор', 'Главный автор'), ('Соавтор', 'Соавтор'), ('Помощник', 'Помощник')], verbose_name='Роль')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='Книга')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.writer', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'запись о роли автора в книге',
                'verbose_name_plural': 'Роли авторов в книгах',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='id_writer',
            field=models.ManyToManyField(through='books.BookWriter', to='books.writer', verbose_name='id_wr'),
        ),
    ]
