# Generated by Django 5.1.6 on 2025-06-04 09:21

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_orderitem_no_ord_alter_review_rating_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalBook',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('isbn', models.CharField(max_length=17, verbose_name='ISBN')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('photo', models.TextField(verbose_name='Фото')),
                ('genre', models.CharField(choices=[('Фэнтези', 'Фэнтези'), ('Фантастика', 'Фантастика '), ('Любовный роман', 'Любовный роман'), ('Детектив', 'Детектив'), ('Приключения', 'Приключения'), ('Классическая проза', 'Классическая проза'), ('Современная проза', 'Современная проза')], max_length=30, verbose_name='Жанр')),
                ('num_page', models.SmallIntegerField(blank=True, null=True, verbose_name='Страницы')),
                ('year', models.DateTimeField(blank=True, null=True, verbose_name='Год выпуска')),
                ('discount', models.PositiveSmallIntegerField(verbose_name='Цена')),
                ('sale', models.CharField(choices=[('10', '10'), ('15', '15'), ('20', '20'), ('25', '25'), ('30', '30')], max_length=3, null=True, verbose_name='Скидка')),
                ('description', models.TextField(verbose_name='Описание')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('id_publish', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='books.publishinghouse', verbose_name='id_pb')),
            ],
            options={
                'verbose_name': 'historical книгу',
                'verbose_name_plural': 'historical Книги',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
