# Generated by Django 5.0.6 on 2025-06-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='status_feed',
            field=models.CharField(choices=[('Новый', 'Новый'), ('Обработан', 'Обработан')], default='Новый', verbose_name='Статус заявки'),
        ),
    ]
