services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: BooksForEveryone
      POSTGRES_USER: adminBook
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: >
      sh -c "echo 'Ожидание БД...' &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DEBUG: 'True'
      POSTGRES_DB: BooksForEveryone
      POSTGRES_USER: adminBook
      POSTGRES_PASSWORD: 1234
      DB_HOST: db
      DB_PORT: '5432'
    depends_on:
      - db

volumes:
  postgres_data:
